import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // playwright-report/ and test-results/ (Playwright's HTML report and raw
  // run artifacts) and .wrangler/ (the Cloudflare/Nitro build's deploy
  // config) are all gitignored and regenerated by routine `npm test`/`npm
  // run build` runs, but were missing here -- unlike the TS-only rules
  // below (files: "**/*.{ts,tsx}"), eslintPluginPrettier at the bottom of
  // this file applies to every file type with no such scoping, so
  // `eslint .` was reaching into playwright-report/trace/assets/*.js --
  // CodeMirror and other huge minified third-party bundles -- and trying
  // to Prettier-format multi-hundred-KB minified single lines. Turned a
  // multi-second run into 7+ CPU-minutes.
  { ignores: ["dist", ".output", ".vinxi", ".wrangler", "playwright-report", "test-results"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
