-- Corrects the Tanzil Arabic-text content_sources row's license_name from
-- the provisional generic label used when the row was first inserted
-- (migration 20260820100000) to the precise label confirmed directly from
-- the Tanzil text artifact's own embedded copyright block: "Tanzil Quran
-- Text (Uthmani, Version 1.1) ... License: Creative Commons Attribution
-- 3.0". license_url, attribution_required, and modification_restricted are
-- untouched — the earlier row already recorded those correctly from
-- tanzil.net/docs/Text_License.
--
-- Additive/update-only: no schema change, no new rows, no other row
-- touched. Targets the row by its stable identifying fields (content_type,
-- provider_name, dataset_name, edition_identifier, language), not an
-- assumed UUID, since the row's actual id was generated by
-- gen_random_uuid() at INSERT time in migration 20260820100000 and isn't
-- known here. Aborts loudly if it doesn't find exactly one matching row,
-- rather than silently updating zero or more than one.

DO $$
DECLARE
  affected integer;
BEGIN
  UPDATE public.content_sources
  SET license_name = 'Creative Commons Attribution 3.0'
  WHERE content_type = 'arabic_text'
    AND provider_name = 'Tanzil Project'
    AND dataset_name = 'Uthmani Script'
    AND edition_identifier = 'uthmani'
    AND language = 'ar'
    AND license_name = 'Tanzil Quran Text License';

  GET DIAGNOSTICS affected = ROW_COUNT;
  IF affected <> 1 THEN
    RAISE EXCEPTION
      'Expected to update exactly 1 content_sources row (Tanzil arabic_text with the old license_name), affected %. Check whether this migration already ran, or whether the row''s identifying fields no longer match.',
      affected;
  END IF;
END $$;
